version: '3'
services:
  app:
    build: .
    container_name: luizalabs
    command: gunicorn -b 0.0.0.0 src.wsgi:app
    environment:
      - DATABASE_PROTOCOL=postgresql+psycopg2
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=db
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=''
    stdin_open: true
    tty: true
    ports:
      - "8000:8000"
    volumes:
      - .:/opt/app
    depends_on:
      - postgres
    links:
      - postgres
  postgres:
    image: postgres
    container_name: postgresql_luizalabs
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_DB=db
    volumes:
      - "./.data/postgres:/var/lib/postgresql/data"
    ports:
      - 5432:5432
